### ISSUE TITLE
Typo on https://rotki.com/products/

### ISSUE THREAD

**Issue by sbellem** [rotkehlchenio/rotkicom.github.io#5]
Hey, not sure where to report this ... there's a tiny typo under the **Data synchronization** section (*beind --> being*)

> By **beind** a premium user you have the option to upload your account's encrypted database to our server. It can then be synchronized between different devices. It also serves as a backup. The data is encrypted with your password and we can not read it.

**Comment by LefterisJP** [comment]
oh hey @sbellem thanks. The website is not in github. This is for the blog. For anything to do with the website, please refer to discord or the main repo: https://github.com/rotki/rotki/issues/

But in any case thanks for the report, we will fix this.
